#!/bin/sh

BIN_PATH=$(readlink -f "$0")
ROOT_DIR=$(dirname $BIN_PATH)

if [ -z ${LOG_TYPE} ]
then LOG_TYPE="info"
fi

envs="RUST_BACKTRACE=1 RUST_LOG=${LOG_TYPE} ANGORA_BIN_DIR=${ROOT_DIR}/bin"
fuzzer="${ROOT_DIR}/angora_prefix/bin/fuzzer"

cmd="$envs $fuzzer $*"

# echo $cmd
eval $cmd
